### ISSUE TITLE
Can't build apk

### ISSUE THREAD

**Issue by meafs** [FHB369/MEEConnect#1]
There is no **google-services.json** file in the app folder. So I am getting this error in Android Studio:

> Task :app:processDebugGoogleServices FAILED
> Task :app:javaPreCompileDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Asus\Desktop\MEEConnect\app\src\nullnull\debug\google-services.json
  C:\Users\Asus\Desktop\MEEConnect\app\src\debug\nullnull\google-services.json
  C:\Users\Asus\Desktop\MEEConnect\app\src\nullnull\google-services.json
  C:\Users\Asus\Desktop\MEEConnect\app\src\debug\google-services.json
  C:\Users\Asus\Desktop\MEEConnect\app\src\nullnullDebug\google-services.json
  C:\Users\Asus\Desktop\MEEConnect\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
6 actionable tasks: 6 executed

**Comment by meafs** [comment]
![Annotation 2020-03-31 152625](https://user-images.githubusercontent.com/25178594/78010350-15ed0480-7364-11ea-83bf-031085f84a41.png)

**Comment by meafs** [comment]
I tried both methods .Git clone and download zip .It's the same :(

**Comment by FHB369** [comment]
You need to connect to a firebase project to get the google-services.json file. Create a firebase project from your google account and connect it to this project from Android Studio.

**Comment by meafs** [comment]
I know that .But it's your firebase project .So how can I get that ?

**Comment by meafs** [comment]
So connecting any firebase project would do ,right?

**Comment by FHB369** [comment]
Sorry, I can't give you access to my firebase project. Rather I can send you a sample JSON file, which you can import into the firebase realtime database of your project.

**Comment by meafs** [comment]
I AM FROM MECHANICAL DEPARTMENT, VAI. I AM MESSAGING YOU IN LINKED IN.
